# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-26 01:44
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_id', models.CharField(max_length=16, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=128, null=True)),
                ('last_name', models.CharField(blank=True, max_length=128, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('grade_level', models.IntegerField(blank=True, choices=[(0, 'Preschool'), (1, 'First'), (2, 'Second'), (3, 'Third'), (4, 'Fourth'), (5, 'Fifth'), (6, 'Sixth')], null=True)),
                ('town', models.CharField(blank=True, choices=[('BL', 'Bas-Limbe'), ('BN', 'Bazilan'), ('CB', 'Chouchou Bay'), ('PM', 'Port Margot'), ('RT', 'Robert')], max_length=16, null=True)),
                ('education', models.IntegerField(blank=True, choices=[(0, 'None'), (1, 'Some'), (2, 'All')], default=1, null=True)),
                ('health_status', models.IntegerField(blank=True, choices=[(1, 'Home'), (2, 'Often'), (3, 'Constantly'), (4, 'Drug')], default=3, null=True)),
                ('daily_meals', models.IntegerField(blank=True, null=True)),
                ('has_photo', models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'YES')], default=0, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('last_name', 'first_name'),
                'verbose_name_plural': 'children',
            },
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_name', models.CharField(max_length=128, unique=True)),
                ('household_type', models.IntegerField(blank=True, choices=[(1, 'Mother and Father'), (2, 'Mother'), (3, 'Mother and Stepfather'), (4, 'Father'), (5, 'Other'), (6, 'Unknown')], null=True)),
                ('family_members', models.IntegerField(blank=True, null=True)),
                ('father_occupation', models.IntegerField(blank=True, choices=[(1, 'Farmer'), (2, 'Owner'), (3, 'Worker'), (4, 'Trades'), (5, 'Other'), (6, 'Unknown')], null=True)),
                ('mother_occupation', models.IntegerField(blank=True, choices=[(1, 'Farmer'), (2, 'Owner'), (3, 'Worker'), (4, 'Trades'), (5, 'Other'), (6, 'Unknown')], null=True)),
                ('household_income', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=6, null=True)),
                ('have_maid', models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'YES')], default=0, null=True)),
                ('home_type', models.IntegerField(blank=True, choices=[(1, 'Own'), (2, 'Rent'), (3, 'Other')], default=2, null=True)),
                ('construction_type', models.IntegerField(blank=True, choices=[(1, 'Concrete'), (2, 'Earth'), (3, 'Wooden, 2 Room'), (4, 'Wooden, 1 Room')], null=True)),
                ('parent_education', models.IntegerField(blank=True, choices=[(1, 'Neither'), (2, 'Only'), (3, "Didn't"), (4, 'At least')], default=1, null=True)),
                ('parent_abroad', models.IntegerField(blank=True, choices=[(1, 'None'), (2, 'Yes, Other'), (3, 'Yes, Father'), (4, 'Yes, Mother')], default=1, null=True)),
                ('father_alive', models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'YES')], default=1, null=True)),
                ('mother_alive', models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'YES')], default=1, null=True)),
                ('total_children', models.IntegerField(blank=True, null=True)),
                ('children_in_program', models.IntegerField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'families',
            },
        ),
        migrations.AddField(
            model_name='child',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sponsorship.Family'),
        ),
    ]
